# Generated by Django 5.2.4 on 2025-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
