# Generated by Django 5.2.4 on 2025-07-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_alter_timer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timer',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
    ]
