# Generated by Django 5.2.4 on 2025-07-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0003_timer_elapsed_time_timer_is_running_timer_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='elapsed_time',
            field=models.IntegerField(default=0, help_text='Elapsed time in minutes'),
        ),
    ]
