# Generated by Django 5.2.4 on 2025-07-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0004_alter_timer_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
        ),
    ]
