# Generated by Django 5.2.4 on 2025-07-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0005_alter_timer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
