# Generated by Django 5.2.4 on 2025-07-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timers", "0007_timer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timer",
            name="duration",
            field=models.IntegerField(default=0, help_text="Duration in seconds"),
        ),
        migrations.AlterField(
            model_name="timer",
            name="elapsed_time",
            field=models.IntegerField(default=0, help_text="Elapsed time in seconds"),
        ),
    ]
