# Generated by Django 5.2.4 on 2025-07-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_time_spent', models.DurationField()),
                ('productive_time', models.DurationField()),
                ('unproductive_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_time_spent', models.DurationField()),
                ('average_daily_productive_time', models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name='DashboardStat',
        ),
    ]
