# Generated by Django 5.2.4 on 2025-07-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailysummary_weeklysummary_delete_dashboardstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='actual_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
