# Generated by Django 5.0.3 on 2025-07-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='category_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
