# Generated by Django 5.0.3 on 2025-07-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_category_task_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='goal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
