# Generated by Django 5.0.3 on 2025-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time in minutes', null=True),
        ),
    ]
